 create table cars (id bigint generated by default as identity, make varchar(255) not null, model varchar(255) not null, production_date date not null, registration_number varchar(255) not null, vin varchar(255) not null, primary key (id));
 create table owners (id bigint generated by default as identity, contact_info varchar(255) not null, name varchar(255) not null, primary key (id));
 create table ownerships (id bigint generated by default as identity, purchase_date date not null, sale_date date, car_id bigint not null, owner_id bigint not null, primary key (id));
 alter table if exists cars drop constraint if exists UK_i3ldfyekqw49cw6omv99rrfkx;
 alter table if exists cars add constraint UK_i3ldfyekqw49cw6omv99rrfkx unique (registration_number);
 alter table if exists cars drop constraint if exists UK_9iw0yw3wc3fcv3hhjo2gp0hn4;
 alter table if exists cars add constraint UK_9iw0yw3wc3fcv3hhjo2gp0hn4 unique (vin);
 alter table if exists ownerships add constraint FKw9mh2b5aqjjawqp50bws3jqo foreign key (car_id) references cars;
 alter table if exists ownerships add constraint FKnw7qnojxdryaxyxrjv45uvv56 foreign key (owner_id) references owners;
